
export const Lang = {
  en: {
    ManagePlaylist: "Manage Playlist",
    ManagePlaylistTitle: "Manage Playlist",
    LoginPlaylist: "Login to add your playlist",
    Login: "Login",
    home: "Home",
    faqs: "FAQS",
    contact: "Contact",
    WishTvWebsite: "Our platform is the hub for entertainment solutions, boasting an extensive collection of streaming technologies and thoughtfully curated content.",
    WishTvDevice: "Watch SH Player with these compatible streaming devices",
    ActivateDeviceOne: "Activate Devices",
    SwitchMac: "Switch Mac",
    ParentPin: "Parent Pin",
    AccountDetails: "Account Details",
    Logout: "Logout",
    WishTvAboutOne: "SH Player is the most advanced and user-friendly TV media player.",
    WishTvAboutTwo: "With SH Player, you will enjoy your favorite media on your smart TV.",
    MobileVersion: "Mobile version of",
    Available: "is available",
    wishtvAppAboutThree: "Available for Android on Play Store and iOS on App Store.",
    FAQsTitle: "Frequently Asked Questions",
    answerOne: "Does SH Player contain any channels? Where can I get a playlist?",
    questionOne: "No, SH Player application does not include any channels and no information will be provided about where you can get channels or channel packages. Also, application developers are not responsible for the content uploaded to SH Player.",
    answerTwo: "How can I become a certified SH Player provider?",
    questionTwo: "You can apply on the SH Player platform or contact the support team for more information on becoming a certified provider.",
    answerThree: "How can I become a certified SH Player provider?",
    questionThree: "If you experience a loading screen that never finishes, please restart the app or check your internet connection.",
    answerFour: "How can I use SH Player?",
    questionFour: "SH Player is simple to use. Download the app, log in with your credentials, and start enjoying your favorite media.",
    answerFive: "Having trouble finding our app in stores?",
    questionFive: "If you're having trouble finding our app, please ensure you're searching in the correct store for your device's OS (Android or iOS).",
    answerSix: "My MAC address has changed after I switched to another connection type.",
    questionSix: "If your MAC address changed after switching connection types, you might need to contact support for assistance in updating your credentials.",
    SendMessage: "Send Us a Message",
    ContactUs: "Contact Us",
    FullName: "Full Name",
    Email: "Email",
    Subject: "Subject",
    YourMessage: "Type Your message...",
    SendMessageButton: "Send Message",
    About: "About",
    aboutDesc: "SH Player is an Player app that allows you to watch high-quality content on all devices, whether it's your TV, mobile, or Android box, regardless of your internet speed",
    PoliciesConditions: "Policies & Conditions",
    TermsConditions: "Terms & Conditions",
    PrivacyPolicy: "Privacy Policy",
    footer: "Copyright © 2025 SH Player",
    AddPlaylist: "Add Playlist",
    LoadingPlaylists: "Loading playlists...",
    Playlist: "Playlist",
    Actions: "Actions",
    ActivateDevice: "Activate Device",
    Price: "Price",
    PaymentMethod: "Payment method",
    noteOne: "NOTE",
    noteDesc: "SH Player does not provide content and is purely a media player. To use SH Player, you must upload your own playlist. If you don’t have a playlist, you cannot use the SH Player. In this case, do not pay. Also, we do not allow activation for users who do not have a playlist.",
    SwitchDevice: "Switch Device MAC",
    MaxLength: "Max length",
    newMacAddress: "New MAC Address",
    transferMacAddress: "Transfer your activation and playlists to another device MAC Address",
    noteTwo: "NOTE",
    noteDescTwo: "Your device login information, playlists, and activation period shall be transferred to this new device MAC address. Your old MAC address device will no longer be attached to this account.",
    Save: "Save",
    parentPinTitle: "Parent Pin",
    resetParentPIN: "Reset Parent PIN",
    newParentPin: "New Parent Pin",
    noteThree: "NOTE",
    noteDescThree: "If you forgot your parent pin in the app, you can change the parent pin here.",
    AccountDetailsTitle: "Account Details",
    Status: "Status",
    CreationDate: "Creation Date",
    ExpirationDate: "Expiration Date",
    AddPlaylistTitle: "Add Playlist",
    EditPlaylistTitle: "Edit Playlist",
    PlaylistName: "Playlist Name",
    EnterPlaylistName: "Enter Playlist Name",
    PlaylistURL: "Playlist URL",
    EnterPlaylistURL: "Enter Playlist URL",
    ProtectedPlaylist: "Protected Playlist",
    noteFour: "NOTE",
    noteDescFour: "Protected playlists will not be viewed or modified without entering a PIN.",
    Password: "Password",
    EnterPassword: "Enter Password",
    Cancel: "Cancel",
    Saving: "Saving...",
    UpdatePlaylist: "Update Playlist",
    ErrorMessageOne: "An error occurred",
    ErrorMessageTwo: "Playlist URL is required",
    ErrorMessageThree: "Password is required for protected playlists",
    EditErrorMessageOne: "Failed to update playlist",
    EditErrorMessageTwo: "Error updating playlist",
    EditErrorMessageThree: "An error occurred while updating the playlist",
    SaveChanges: "Save Changes",
    AccountDetailstTitle: "Account Details",
    AddPlaylistOne: "Add Playlist",
    AddPlaylistTwo: "Add Playlist",
    Enterplaylistname: "Enter playlist Name",
    EnterplaylistURL: "Enter Playlist URL",
    Enterpassword: "Enter password",
    EditPlaylist: "Edit Playlist",
    PlaylistNameOne: "Playlist Name",
    PlaylistURLOne: "Playlist URL",
    PasswordOne: "Password",
    EnterpasswordOne: "Enter password",
    wishtvAboutone: "SH Player is the most advanced and user-friendly TV media player.",
    wishtvAboutTwo: "With SH Player, you will enjoy your favorite media on your smart TV.",
  },
  ar: {
    ManagePlaylist: "إدارة قائمة التشغيل الخاصة بك",
    LoginPlaylist: "قم بتسجيل الدخول لإضافة قائمة التشغيل الخاصة بك",
    Login: "تسجيل الدخول",
    home: "الرئيسية",
    faqs: "الأسئلة الشائعة",
    contact: "تواصل معنا",
    WishTvWebsite: "منصتنا هي المركز لحلول الترفيه، وتتميز بمجموعة واسعة من تقنيات البث والمحتوى المختار بعناية.",
    WishTvDevice: "شاهد خدمات تطبيقنا باستخدام اجهزة البث المتوافقه",
    ManagePlaylistTitle: "إدارة قائمة التشغيل",
    ActivateDeviceOne: "تفعيل الأجهزة",
    SwitchMac: "تبديل الماك",
    ParentPin: "رمز التحكم العائلى",
    AccountDetails: "تفاصيل الحساب",
    Logout: "تسجيل الخروج",
    wishtvAboutone: "تطبيقنا هو مشغل الوسائط التلفزيونية الأكثر تقدمًا وسهولة في الاستخدام.",
    wishtvAboutTwo: "مع تطبيقنا، سوف تستمتع بالوسائط المفضلة لديك على التلفزيون الذكي الخاص بك.",
    MobileVersion: "النسخة المحمولة من",
    available: "متاحه",
    wishtvAppAboutThree: "متاح لنظام الاندرويد على بلاى ستور ولاجهزة الايفون على اب ستور",
    faqsTitle: "الأسئلة الشائعة",
    answerOne: "هل يحتوي تطبيقنا على أي قنوات؟ أين يمكنني الحصول على قائمة تشغيل؟",
    questionOne: "لا، لا يتضمن تطبيقنا أي قنوات ولن يتم تقديم أي معلومات حول المكان الذي يمكنك الحصول فيه على القنوات أو باقات القنوات. كما أن مطوري التطبيق غير مسؤولين عن المحتوى الذي يتم تحميله على Wish TV.",
    answerTwo: "كيف يمكنني أن أصبح مقدم خدمة ويش تى فى معتمدًا؟",
    questionTwo: "يمكنك التقديم على منصة ويش تى فى أو التواصل مع فريق الدعم للحصول على مزيد من المعلومات حول كيفية أن تصبح مقدم خدمة معتمدًا.",
    answerThree: "هل لديك شاشة تحميل لا تنتهي؟",
    questionThree: "إذا واجهت شاشة تحميل لا تنتهي أبدًا، فيرجى إعادة تشغيل التطبيق أو التحقق من اتصالك بالإنترنت.",
    answerFour: "كيف يمكنني استخدام ويش تى فى؟",
    questionFour: "يعد استخدام تطبيقنا سهلاً. قم بتنزيل التطبيق، وسجّل الدخول باستخدام بيانات الاعتماد الخاصة بك، وابدأ في الاستمتاع بالوسائط المفضلة لديك.",
    answerFive: "هل تواجه مشكلة في العثور على تطبيقنا في المتاجر؟",
    questionFive: "إذا كنت تواجه مشكلة في العثور على تطبيقنا، فيرجى التأكد من أنك تبحث في المتجر الصحيح لنظام التشغيل الخاص بجهازك (اندرويد أو ايفون).",
    answerSix: "لقد تغير عنوان ماك الخاص بي بعد أن قمت بالتبديل إلى نوع اتصال آخر.",
    questionSix: "إذا تغير عنوان ماك الخاص بك بعد تبديل أنواع الاتصال، فقد تحتاج إلى الاتصال بالدعم للحصول على المساعدة في تحديث بيانات الاعتماد الخاصة بك.",
    SendMessage: "أرسل لنا رسالة",
    ContactUs: "تواصل معنا",
    FullName: "الاسم بالكامل",
    Email: "البريد الالكترونى",
    Subject: "الموضوع",
    YourMessage: "اكتب رسالتك هنا",
    SendMessageButton: "ارسل رسالة",
    About: "من نحن",
    aboutDesc: "SH Player هو تطبيق مشغل يسمح لك بمشاهدة محتوى عالي الجودة على جميع الأجهزة، سواء كان جهاز التلفزيون أو الهاتف المحمول أو جهاز Android، بغض النظر عن سرعة الإنترنت لديك`",
    PoliciesConditions: "السياسات والشروط",
    TermsConditions: "الشروط والأحكام",
    PrivacyPolicy: "سياسة الخصوصية",
    footer: "جميع الحقوق محفوظة © 2025 قناة SH Player",
    AddPlaylist: "إضافة قائمة التشغيل",
    LoadingPlaylists: "جاري تحميل قوائم التشغيل...",
    Playlist: "قائمة التشغيل",
    Actions: "الإجراءات",
    ActivateDevice: "تفعيل الجهاز",
    Price: "السعر",
    PaymentMethod: "طريقة الدفع",
    noteOne: "ملحوظة",
    noteDesc: "لا يوفر تطبيقنا أي محتوى، وهو عبارة عن مشغل وسائط فقط. لاستخدام تطبيقنا، يتعين عليك تحميل قائمة التشغيل الخاصة بك. إذا لم يكن لديك قائمة تشغيل، فلن تتمكن من استخدام مشغل ويش بعد الآن، لذا في هذه الحالة لا تدفع. كما أننا لا نسمح بالتنشيط للمستخدمين الذين ليس لديهم قوائم تشغيل.",
    SwitchDevice: "تبديل جهاز MAC",
    MaxLength: "الحد الاقصى",
    newMacAddress: "عنوان MAC الجديد",
    transferMacAddress: "نقل التنشيط وقوائم التشغيل إلى عنوان MAC لجهاز آخر",
    noteTwo: "ملحوظة",
    noteDescTwo: "سيتم نقل معلومات تسجيل الدخول الخاصة بجهازك وقوائم التشغيل وفترة التنشيط إلى عنوان MAC الجديد الخاص بهذا الجهاز. لن يكون عنوان MAC القديم الخاص بك مرتبطًا بهذا الحساب بعد الآن.",
    Save: "حفظ",
    parentPinTitle: "رمز التحكم العائلى",
    resetParentPIN: "إعادة تعيين رقم التعريف الشخصي للوالدين",
    newParentPin: "رمز الجديد التحكم العائلى",
    noteThree: "ملحوظة",
    noteDescThree: "إذا نسيت رمز التعريف الشخصي الأساسي الخاص بك في التطبيق، فيمكنك تغيير رمز التعريف الشخصي الأساسي هنا.",
    AccountDetailsTitle: "تفاصيل الحساب",
    Status: "حالة",
    CreationDate: "تاريخ الأنشاء",
    ExpirationDate: "تاريخ الأنتهاء",
    AddPlaylistOne: "إضافة قائمة التشغيل",
    AddPlaylistTwo: "إضافة قائمة التشغيل",
    EditPlaylistOne: "تعديل قائمة التشغيل",
    PlaylistName: "اسم قائمة التشغيل",
    EnterPlaylistName: "أدخل اسم قائمة التشغيل",
    PlaylistURL: "رابط قائمة التشغيل",
    EnterPlaylistURL: "أدخل عنوان URL لقائمة التشغيل",
    ProtectedPlaylist: "قائمة التشغيل المحمية",
    noteFour: "ملحوظة",
    noteDescFour: "لن يتم عرض قوائم التشغيل المحمية أو تعديلها دون إدخال رقم التعريف الشخصي (PIN)",
    Password: "كلمة المرور",
    EnterPassword: "ادخل كلمة المرور",
    Cancel: "إلغاء",
    Saving: "جارى التعديل...",
    UpdatePlaylist: "تحديث قائمة التشغيل",
    errorMessageOne: "اسم قائمة التشغيل مطلوب",
    errorMessageTwo: "مطلوب عنوان URL لقائمة التشغيل",
    errorMessageThree: "مطلوب كلمة مرور لقوائم التشغيل المحمية",
    EditErrorMessageOne: "فشل في تحديث قائمة التشغيل",
    EditErrorMessageTwo: "خطأ في تحديث قائمة التشغيل:",
    EditErrorMessageThree: "حدث خطأ أثناء تحديث قائمة التشغيل",
    EditPlaylist: "تعديل قائمة التشغيل",
    PlaylistNameOne: "اسم قائمة التشغيل",
    PlaylistURLOne: "رابط قائمة التشغيل",
    PasswordOne: "كلمة المرور",
    EnterPasswordOne: "ادخل كلمة المرور",
    SaveChanges: "حفظ التغيرات",
    AccountDetailstTitle: "تفاصيل الحساب",
    Enterplaylistname: "أدخل اسم قائمة التشغيل",
    EnterplaylistURL: "أدخل عنوان URL لقائمة التشغيل",
    Enterpassword: "ادخل كلمة المرور",
  }
}